spring:
  application:
    name: TuPagoTemplate
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    password: ''
    driver-class-name: org.postgresql.Driver
    username: TuPagoTemplate
    url: jdbc:postgresql://localhost:5432/TuPagoTemplate
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      url: redis://localhost:6379
      database: 0
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: true
        generate_statistics: false
        order_updates: true
        order_inserts: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    open-in-view: false
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: TuPagoTemplate-scheduling-
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: TuPagoTemplate-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com:
      mycompany:
        myapp: INFO
      tupago: INFO
kafka:
  producer:
    '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
    '[value.serializer]': org.apache.kafka.common.serialization.StringSerializer
  consumer:
    '[auto':
      offset.reset]: earliest
    '[value.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
    '[group.id]': myapp
  polling:
    timeout: 10000
  topic:
    dummy: queue.TuPagoTemplate.dummy
  bootstrap-servers: localhost:9092
application:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  logging:
    logstash:
      tcp:
        shutdown_grace_period: PT1M
        enabled: false
        ring-buffer-size: 8192
        host: localhost
        port: 5000
management:
  endpoints:
    web:
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
      base-path: /management
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
server:
  port: 8080
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
  enable-native-support: true
jhlite-hidden-resources:
  tags: banner
  # Disable the modules and its dependencies by slugs
  slugs: custom-jhlite
